name: checkin

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '18 15 * * *'

jobs:
  v-checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Set python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: 
        python -m pip install --upgrade requests
        python -m pip install --upgrade pip
    
    - name: v.qq.com check in
      run: |
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        login_cookie='${{ secrets.V_COOKIE_LOGIN }}'
        signin_cookie='${{ secrets.V_COOKIE_SIGNIN }}'
        auth_refresh_url='${{ secrets.V_AUTH_REFRESH_URL }}'
        
        python3 main.py <<EOF
        ${sckey}
        ${login_cookie}
        ${signin_cookie}
        ${auth_refresh_url}
        EOF
